### ISSUE TITLE
How to import JSON

### ISSUE THREAD

**Issue by DavidHenryThoreau** [hydrargyrum/breakthesilence#1]
I've followed your tutorial, in then end i get the silence-backup.json, i also tried to indent with python -m json.tool silence-backup.json > silence-backup_indent.json but How can i import this json to my Android database ?
I've tried to install this app => https://f-droid.org/fr/packages/com.github.tmo1.sms_ie/ but it does not import  silence-backup.json

**Comment by hydrargyrum** [comment]
@DavidHenryThoreau, there is currently no way to do so. However, I will probably write a converter from breakthesilence/Epistolaire format to [sms I/E](https://f-droid.org/fr/packages/com.github.tmo1.sms_ie/)'s format, so it can be imported.

**Comment by DavidHenryThoreau** [comment]
@hydrargyrum Nice idea, after that I'll move to default Android/LineageOS SMS application (Silence development seems stopped  Silence seems to freeze in Android 12 https://git.silence.dev/Silence/Silence-Android/-/issues/838)

**Comment by DavidHenryThoreau** [comment]
Do you have work on it ? 
I can help you to test features if you want.

**Comment by hydrargyrum** [comment]
@DavidHenryThoreau  Unfortunately, not yet.
I investigated quickly but noticed SMS I/E app saves and restores contact info (id and some other fields) in their format, while neither epistolaire nor breakthetilence do. This makes the conversion not as straightforward as I initially thought.
So:
- either the epistolaire conversion tool for SMS I/E can generate fake contacts based on the phone numbers and skip all other contact info without problems
- or it will be necessary to patch epistolaire and breakthesilence to gather contact info in order to inject it in the conversion tool for SMS I/E app.

That's what should be investigated now but I didn't have time with it yet.

**Comment by DavidHenryThoreau** [comment]
@hydrargyrum Did you take time to investigate ?
